[build]
  publish = "."

[[redirects]]
  from = "/inbound.html"
  to = "/inbound-programmes/"
  status = 301

[[redirects]]
  from = "/outbound.html"
  to = "/outbound-programmes/"
  status = 301

[[redirects]]
  from = "/partnerships.html"
  to = "/partnership/"
  status = 301

[[redirects]]
  from = "/contact.html"
  to = "/contact/"
  status = 301
